version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          name: UnitTest
          command: python -m unittest Tests.unit_testing
      - run:
          name: IntegrationTest
          command: python -m unittest Tests.integration_testing

workflows:
  main:
    jobs:
      - build-and-test
